name: CI/CD React App to DigitalOcean

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read
      contents: read

    defaults:
      run:
        working-directory: ./hospital-react-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes in frontend app
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'hospital-react-app/**'

      - name: Setup Node.js
        if: steps.filter.outputs.frontend == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        if: steps.filter.outputs.frontend == 'true'
        run: npm install

      - name: Build React App
        if: steps.filter.outputs.frontend == 'true'
        env:
          VITE_TINYMCE_API_KEY: ${{ secrets.TINYMCE_API_KEY }}
          VITE_API_URL: https://api.demoproject.software/api
        run: npm run build

      # Create deployment archive
      - name: Create deployment archive
        if: steps.filter.outputs.frontend == 'true'
        run: |
          cd dist
          tar -czf ../frontend-deploy.tar.gz .

      # Stop container and clean directory
      - name: Stop container and clean directory
        if: steps.filter.outputs.frontend == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          script: |
            cd /root/nginx-proxy-manager
            docker-compose stop frontend-server
            rm -rf /var/www/hospital-react-app/*

      # Upload and deploy
      - name: Upload build files
        if: steps.filter.outputs.frontend == 'true'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          source: "hospital-react-app/frontend-deploy.tar.gz"
          target: "/var/www/hospital-react-app"
          strip_components: 1

      # Extract and start container
      - name: Extract files and start container
        if: steps.filter.outputs.frontend == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          script: |
            cd /var/www/hospital-react-app
            tar -xzf frontend-deploy.tar.gz
            rm frontend-deploy.tar.gz
            sudo chown -R www-data:www-data .
            sudo find . -type d -exec chmod 755 {} \;
            sudo find . -type f -exec chmod 644 {} \;
            cd /root/nginx-proxy-manager
            docker-compose start frontend-server
